import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";

const lamaSans = localFont({
  src: "../public/fonts/LamaSans-Regular.ttf",
  variable: "--font-lama-sans",
  display: "swap",
});

const larkenDemo = localFont({
  src: "../public/fonts/LarkenDEMO-Regular.otf",
  variable: "--font-larken-demo",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lamaSans.variable} ${larkenDemo.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
